export const constants = {
  domain: 'https://dummyimage.com/',
  text: `Marshmallow cheesecake chupa chups cake croissant. Lemon drops tart sweet lollipop sesame snaps cotton candy jelly beans cheesecake wafer. Cupcake soufflé macaroon marshmallow dessert cookie halvah caramels. Wafer gummies lollipop bear claw ice cream carrot cake. Marshmallow biscuit gingerbread fruitcake marzipan chocolate bar croissant. Tootsie roll carrot cake apple pie lollipop cake bonbon. Donut croissant sesame snaps lollipop dessert marshmallow candy canes. Icing chocolate cotton candy. Sugar plum chupa chups bonbon pudding gingerbread marshmallow. Gummi bears chocolate cake liquorice. Pastry croissant pastry cupcake toffee croissant lollipop jujubes pastry. Jujubes powder biscuit bear claw cheesecake tiramisu cookie liquorice. Topping cupcake lollipop.

Cake chocolate bar biscuit jelly pudding halvah. Toffee toffee apple pie. Jelly toffee toffee marshmallow chocolate dragée. Candy canes cheesecake danish cake pie dessert. Halvah cheesecake lollipop powder tiramisu. Muffin macaroon dessert caramels gingerbread carrot cake. Pie cupcake danish powder oat cake powder muffin gummies. Gummies carrot cake tootsie roll jelly-o bear claw croissant. Lemon drops candy apple pie bonbon cake gummies. Gummi bears danish macaroon jujubes carrot cake toffee soufflé cake halvah. Pastry pastry tootsie roll ice cream icing pastry fruitcake ice cream. Toffee tiramisu bonbon gummi bears wafer pie icing lemon drops ice cream. Sugar plum caramels danish cake topping pudding. Muffin tootsie roll candy.

Sweet roll donut croissant danish. Cake cupcake halvah cheesecake candy canes ice cream lollipop bear claw. Croissant brownie macaroon cake cheesecake cotton candy jujubes. Danish pudding jelly lemon drops chocolate pudding gingerbread gummies tiramisu. Cupcake pastry cupcake donut icing dessert caramels cookie. Sweet roll tart icing cupcake jelly sugar plum. Cupcake croissant wafer candy canes. Dessert chocolate cake biscuit candy sweet apple pie candy sugar plum. Tart croissant chocolate cake sugar plum cupcake jelly-o soufflé jelly. Tiramisu lemon drops jelly-o lemon drops caramels dragée. Jelly beans biscuit cheesecake cookie jelly-o. Sesame snaps chocolate icing cupcake donut topping carrot cake. Gingerbread carrot cake tiramisu.

Jelly beans cake tootsie roll gingerbread cake. Bonbon croissant gummies ice cream. Pudding bonbon jujubes jujubes dragée chupa chups pie chocolate bar biscuit. Cookie pie liquorice sesame snaps chocolate cake dessert. Gummi bears sweet jelly-o apple pie gummi bears. Dragée cotton candy marzipan chocolate cake carrot cake. Sweet roll donut marshmallow. Donut liquorice muffin dessert. Tart dessert tart apple pie jelly-o oat cake. Cake jelly cake macaroon ice cream cake jelly tootsie roll. Muffin cookie icing cake chocolate cake dessert fruitcake chupa chups. Sweet cupcake cake cake donut carrot cake cake caramels pie. Wafer marzipan chocolate marshmallow sesame snaps pastry danish sweet. Oat cake candy canes pudding jelly-o chocolate cake.

Topping cheesecake topping cupcake marzipan. Chocolate bar chocolate bar croissant croissant liquorice marzipan chocolate sweet roll cheesecake. Liquorice icing marzipan brownie candy. Cake pastry cake. Marshmallow topping chocolate cake donut. Jelly apple pie jelly carrot cake croissant. Cake croissant ice cream lemon drops apple pie halvah jelly-o cake tiramisu. Brownie fruitcake wafer oat cake fruitcake gummies tart sweet. Dragée tootsie roll croissant topping lollipop. Pie topping chocolate wafer bear claw jelly-o pie jelly marshmallow. Sugar plum donut oat cake dessert cake tootsie roll pastry sesame snaps. Biscuit soufflé chocolate macaroon chupa chups. Ice cream candy candy brownie apple pie.

Jujubes sweet brownie icing biscuit tootsie roll topping. Croissant croissant marshmallow toffee. Powder fruitcake brownie muffin gummi bears cupcake donut. Gingerbread cupcake cookie dessert. Lollipop tiramisu jelly-o gingerbread jujubes brownie fruitcake. Soufflé cookie danish jelly-o. Cookie powder icing. Gingerbread jelly icing oat cake liquorice candy canes jelly pie marshmallow. Bonbon sesame snaps fruitcake wafer pastry. Carrot cake carrot cake sesame snaps pastry. Tootsie roll powder cupcake bear claw jelly pastry sugar plum muffin lemon drops. Marzipan lemon drops brownie lemon drops croissant jujubes marshmallow bear claw.

Ice cream biscuit jelly-o halvah icing powder cotton candy icing soufflé. Cookie cotton candy fruitcake sweet jelly pie danish. Chocolate cake toffee tiramisu tart pie. Danish chupa chups gingerbread cheesecake pudding chocolate bar gingerbread chocolate bar. Muffin cotton candy toffee sugar plum. Sesame snaps tootsie roll jujubes cupcake chocolate bar toffee. Cupcake brownie dessert chupa chups. Chocolate bar cheesecake chocolate bar cake dragée cotton candy donut tiramisu pudding. Lollipop carrot cake brownie powder topping cake jelly-o powder chocolate. Candy canes cookie jelly tiramisu bonbon bear claw sweet roll carrot cake icing. Icing oat cake jelly-o jelly topping liquorice. Sugar plum cookie tart cotton candy wafer sugar plum. Dragée soufflé cake cake.

Muffin brownie pudding jelly liquorice macaroon jujubes cotton candy. Ice cream gummies chocolate bar tart powder chocolate cake. Bonbon chocolate cake cake cheesecake. Oat cake pastry wafer chupa chups jelly bear claw sesame snaps icing. Tiramisu jelly-o cheesecake cheesecake sweet ice cream lemon drops. Macaroon jelly-o cake oat cake tootsie roll cupcake cotton candy chocolate. Apple pie bear claw dragée fruitcake. Chocolate cupcake pastry dragée cake. Pudding biscuit marzipan topping. Gummi bears liquorice tootsie roll. Tart icing soufflé pie apple pie. Donut lemon drops cake. Gingerbread dragée muffin cake cotton candy marshmallow candy canes. Gingerbread oat cake macaroon jelly.

Soufflé muffin biscuit. Donut cake apple pie topping. Tootsie roll biscuit halvah. Jelly-o marshmallow bonbon caramels. Bonbon dessert dragée. Icing sugar plum liquorice toffee. Bonbon liquorice jelly-o gummi bears cupcake sweet roll halvah bear claw cake. Chocolate bar chupa chups fruitcake biscuit soufflé marzipan muffin pastry. Donut sweet roll brownie brownie bonbon biscuit liquorice tiramisu. Gummies candy canes tootsie roll danish tart. Lemon drops ice cream dessert caramels cookie. Icing jelly beans cotton candy gummi bears fruitcake powder pastry bonbon. Sweet roll biscuit lemon drops muffin candy canes macaroon.

Jelly-o jelly beans sweet roll. Carrot cake jujubes macaroon pie. Biscuit cotton candy oat cake. Bear claw toffee marshmallow gummi bears. Pudding ice cream liquorice lollipop pudding gingerbread. Candy canes marshmallow jujubes ice cream icing cake. Fruitcake dragée jelly cookie marshmallow lollipop fruitcake toffee wafer. Jujubes cookie cake cake cake bear claw sweet jelly. Chocolate bear claw candy canes chocolate. Liquorice jelly croissant dragée sweet roll. Gummi bears pastry powder candy marzipan bonbon. Cupcake donut cotton candy sesame snaps chocolate oat cake croissant bonbon chocolate bar.`,
  paragraphWords: 200,
  maxParagraphs: 25,
};
